#include "about.h"
#include "font.h"
#include "imgload.h"
#include "layer_draw.h"
#include "version.h"

#include <cstring>

/*
 * ABOUT window implementation: logo on the left, text info on the right.
 * The logo is embedded in the ELF via xxd and drawn as a separate quad.
 */

/* Version banner strings. On the PSP port these came from -D defines in
 * the Makefile; here they fall back to the core VERSION plus a port tag. */
#ifndef APP_VERSION
#define APP_VERSION VERSION
#endif
#ifndef VERSION_INFO
#define VERSION_INFO "trimui"
#endif

/* Embedded PNG data from src/logo_data.cpp (generated by xxd -i) */
extern unsigned char assets_logo16_png[];
extern unsigned int assets_logo16_png_len;

/* Pad mask for closing the window. */
enum {
    ABOUT_PAD_BACK = 0x08,  /* CIRCLE/START - close */
};

AboutWindow::AboutWindow() :
    open_flag(false), logo_w(0), logo_h(0), logo_loaded(false), logo_upload(false)
{
    reset_input_state();
    panel_w = PANEL_W;
    panel_h = PANEL_H;
}

void AboutWindow::open()
{
    if (open_flag.load(std::memory_order_relaxed))
        return;
    
    if (!logo_loaded) {
        init_logo();
    }
    
    reset_input_state();
    mark_dirty();
    open_flag.store(true, std::memory_order_release);
}

void AboutWindow::close()
{
    open_flag.store(false, std::memory_order_release);
}

void AboutWindow::update(unsigned pad)
{
    if (!open_flag.load(std::memory_order_relaxed))
        return;

    /* Close on CIRCLE or START (keyup edge). */
    if (keyup_edge(pad, ABOUT_PAD_BACK)) {
        close();
    }

    prev_pad = pad;
}

void AboutWindow::init_logo()
{
    logo_loaded = true;
    
    /* Load PNG from embedded data. */
    int w = 0, h = 0;
    
    if (img_load_from_memory(
            assets_logo16_png,
            assets_logo16_png_len,
            logo_tex, LOGO_TEX_W, LOGO_TEX_H, &w, &h)) {
        logo_w = w;
        logo_h = h;
        logo_upload = true;
    } else {
        /* Logo not available - that's fine, we just won't draw it. */
        logo_w = 0;
        logo_h = 0;
    }
}

void AboutWindow::paint()
{
    /* Snapshot the sequence first. */
    const unsigned seq = snapshot_seq();

    /* Override panel background to pure black. */
    clut[C_PANEL_BG] = 0xff000000u; /* A B G R = fully opaque black */

    /* Panel background. */
    fill_rect(0, 0, panel_w, panel_h, C_PANEL_BG);

    /* Text info on the right side. */
    struct TextLine {
        const char * text;
        uint8_t color;
        bool double_size;  /* true = 2x font, false = normal */
    };

    static const TextLine lines[] = {
        { "VECTOR-06C",                                     C_TEXT_WHITE, true  },
        { "EMULATOR",                                       C_TEXT_WHITE, true  },
        { "FOR TRIMUI",                                     C_TEXT_WHITE, true  },
        { "VERSION: " APP_VERSION " (" VERSION_INFO ")",    C_TEXT_WHITE, false },
        { "",                                               C_TEXT_WHITE, false },  /* spacer */
        { "DEVELOPER:",                                     C_TEXT_WHITE, true  },
        { "SARMIN ALEXEY",                                  C_TEXT_WHITE, true  },
        { "SITE: HTTPS://SARMIN.RU",                        C_TEXT_WHITE, false },
    };
    static const int LINE_COUNT = sizeof(lines) / sizeof(lines[0]);

    const int line_h = OVERLAY_FONT_H * 2 + 4;
    int y = PAD_Y + 8;

    for (int i = 0; i < LINE_COUNT; ++i) {
        const TextLine & l = lines[i];
        if (l.text[0] != '\0') {
            if (l.double_size)
                print_text2x(TEXT_X, y, l.text, l.color);
            else
                print_text(TEXT_X, y, l.text, l.color);
        }
        y += line_h;
    }

    finish_paint(seq);
}

void AboutWindow::draw()
{
    /* Draw the base panel quad. */
    Popup::draw();
    
    /* Draw the logo quad on top if available. */
    if (logo_loaded && logo_w > 0) {
        draw_logo();
    }
}

void AboutWindow::draw_logo()
{
    if (logo_upload) {
        logo_upload = false;
    }

    /* Panel is centered on screen (480x272). */
    const float panel_x = ((float)LAYER_SCREEN_W - PANEL_W) / 2.0f;
    const float panel_y = ((float)LAYER_SCREEN_H - PANEL_H) / 2.0f;

    /* Logo position: left side of the panel. */
    const float screen_x = panel_x + PAD_X;
    const float screen_y = panel_y + PAD_Y;
    const float disp_w = LOGO_SIZE;
    const float disp_h = LOGO_SIZE;

    layer_draw_rgba_quad(
        logo_tex, LOGO_TEX_W, LOGO_TEX_H,
        screen_x, screen_y, disp_w, disp_h,
        0, 0, logo_w, logo_h,
        true,  /* bilinear filtering */
        false  /* upload already handled */
    );
}
